Fix GUC timescaledb.enable_job_execution_logging
Since: https://github.com/timescale/timescaledb/pull/7131 the context of GUC
`timescaledb.enable_job_execution_logging` changed to PGC_SIGHUP and it means
that now it will only work either changing postgresql.conf or using ALTER SYSTEM

Before the context was PGC_USERSET, and with this context was possible to set at
session, database or user level. Setting it at database or user level create an
entry in the `pg_catalog.pg_db_role_setting` Postgres metadata table. Now after
changing the default context PG_USERSET to PG_SIGHUP make impossible to reset
this GUC from database/user level leading to the following error:

  tsdb=> alter database tsdb reset timescaledb.enable_job_execution_logging;
  ERROR:  parameter "timescaledb.enable_job_execution_logging" cannot be changed now

So this script will remove potential `timescaledb.enable_job_execution_logging`
entries from `pg_catalog.pg_db_role_setting` and set it at system level using
`ALTER SYSTEM` statement when necessary

WARNING! this script *SHOULD* be executed by a *SUPERUSER* using `psql` console.